openapi: 3.0.3
info:
  title: Products Management API
  description: API for managing products with inventory tracking
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all products
      operationId: getAllProducts
      tags:
        - Products
      parameters:
        - name: category
          in: query
          required: false
          description: Filter products by category ID
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: limit
          in: query
          required: false
          description: Maximum number of products to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          required: false
          description: Number of products to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer
                    description: Total number of products
                  limit:
                    type: integer
                    description: Number of products per page
                  offset:
                    type: integer
                    description: Number of products skipped
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create a new product
      description: Create a new product (id is auto-generated, category is mandatory)
      operationId: createProduct
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /products/{id}:
    get:
      summary: Get product by ID
      description: Retrieve a specific product by its ID
      operationId: getProductById
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Update product
      description: Update an entire product (id is required, category is mandatory)
      operationId: updateProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    patch:
      summary: Partially update product
      description: Partially update a product (id is required)
      operationId: patchProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Delete product
      description: Delete a product by ID
      operationId: deleteProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Product deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Inventory:
      type: object
      required:
        - productId
        - quantity
        - quantityReserved
      properties:
        id:
          type: integer
          format: int64
          description: Inventory ID (auto-generated)
          example: 1
        productId:
          type: integer
          format: int64
          description: Product ID this inventory belongs to
          example: 123
        quantity:
          type: integer
          description: Available quantity
          minimum: 0
          example: 100
        quantityReserved:
          type: integer
          description: Reserved quantity
          minimum: 0
          example: 10

    Product:
      type: object
      required:
        - id
        - category
        - name
        - description
        - price
        - inventory
      properties:
        id:
          type: integer
          format: int64
          description: Product ID
          example: 123
        category:
          type: integer
          format: int64
          description: Category ID this product belongs to
          example: 1
        name:
          type: string
          description: Product name
          example: "Wireless Headphones"
        description:
          type: string
          description: Product description
          example: "High-quality wireless headphones with noise cancellation"
        price:
          type: number
          format: double
          description: Product price
          minimum: 0
          example: 199.99
        inventory:
          $ref: '#/components/schemas/Inventory'

    ProductCreate:
      type: object
      required:
        - category
        - name
        - description
        - price
        - inventory
      properties:
        category:
          type: integer
          format: int64
          description: Category ID this product belongs to (mandatory)
          example: 1
        name:
          type: string
          description: Product name
          example: "Wireless Headphones"
        description:
          type: string
          description: Product description
          example: "High-quality wireless headphones with noise cancellation"
        price:
          type: number
          format: double
          description: Product price
          minimum: 0
          example: 199.99
        inventory:
          type: object
          required:
            - productId
            - quantity
            - quantityReserved
          properties:
            productId:
              type: integer
              format: int64
              description: Product ID this inventory belongs to (will be set automatically)
              example: 123
            quantity:
              type: integer
              description: Available quantity
              minimum: 0
              example: 100
            quantityReserved:
              type: integer
              description: Reserved quantity
              minimum: 0
              example: 10

    ProductUpdate:
      type: object
      properties:
        category:
          type: integer
          format: int64
          description: Category ID this product belongs to (optional for partial updates)
          example: 1
        name:
          type: string
          description: Product name
          example: "Wireless Headphones"
        description:
          type: string
          description: Product description
          example: "High-quality wireless headphones with noise cancellation"
        price:
          type: number
          format: double
          description: Product price
          minimum: 0
          example: 199.99
        inventory:
          type: object
          properties:
            productId:
              type: integer
              format: int64
              description: Product ID this inventory belongs to
              example: 123
            quantity:
              type: integer
              description: Available quantity
              minimum: 0
              example: 100
            quantityReserved:
              type: integer
              description: Reserved quantity
              minimum: 0
              example: 10

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "An error occurred"
        code:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        details:
          type: object
          description: Additional error details
          additionalProperties: true

  responses:
    BadRequest:
      description: Bad request - Invalid input data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Invalid input data"
            code: "VALIDATION_ERROR"
            details:
              field: "name"
              reason: "Name is required"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Resource not found"
            code: "NOT_FOUND"

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            message: "Internal server error"
            code: "INTERNAL_ERROR"

tags:
  - name: Products
    description: Product management operations
