@HOST=http://localhost:8080

###
POST {{HOST}}/json
Accept: application/json

{
  "name": "Clothes",
  "description": "Mens Clothes"
}

###
POST {{HOST}}/categories
Content-Type: application/json
Accept: application/json

{
    "name": "Electronics",
    "description": "Electronics Items",
    "products" : [
        {
            "name": "Laptop",
            "description": "Laptop",
            "price": 1000,
            "inventory": {
                "quantity": 10
            }
        },
        {
            "name": "Mobile",
            "description": "Mobile",
            "price": 500
        }
    ]
}

### PATCH/1
PATCH {{HOST}}/categories/1
Content-Type: application/json
Accept: application/json

{
    "description": "Mens & Women Clothes"
}

### GET/1
GET {{HOST}}/categories/1
Accept: application/json


### PUT/1
PUT {{HOST}}/categories/1
Content-Type: application/json
Accept: application/json

{
    "id": 1,
    "name": "Electronics",
    "description": "Electronics Goods"
}

### GET/1
GET {{HOST}}/categories/1
Accept: application/json

### GET
GET {{HOST}}/categories
Accept: application/json
